# Generated by Django 5.0 on 2023-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_link',
            field=models.URLField(max_length=100),
        ),
    ]
